### ISSUE TITLE
urdf parser: bug in parsing floating joints

### ISSUE THREAD

**Issue by anna-seppala** [humanoid-path-planner/hpp-model-urdf#5]
The urdf parser is unable to deal with joints that have type "floating".  If such a joint is defined in the urdf file, the createFreeflyerJoint method is called but is functionality is not applicable to a floating-joint case. The method should be revised and maybe separated into two functions (one to create a rootjoint and another to create an arbitrary floating joint).
In its current form, the method throws an error if the urdf contains floating joints.

**Comment by jmirabel** [comment]
I'm closing this even though the current solution is not very clean.
