### ISSUE TITLE
Problem in the value of inertia matrix

### ISSUE THREAD

**Issue by nmansard** [humanoid-path-planner/hpp-model-urdf#9]
When comparing the values of the inertia matrices in hpp::model::urdf and hpp::pinocchio, the values in hpp::model seem incorrect (indeed, correct values, but wrong order inside the matrix). It is not straight forward to compare, because the matrices in model and in pinocchio are not expressed in the same frame. However, I am quite confident with my test (tbody in hpp-pinocchio). 

Since nobody seriously used the inertia matrices of hpp::model, I simply post this issue for information, and do not investigate further the problem.

**Comment by nmansard** [comment]
Indeed: the matrix is not even symmetric. Example with RShoulderYawLink in Romeo:
I = [-1.07417e-06 0.000664209 5.98521e-06;0.000617202 5.98521e-06 0.000742356;0.00649989 -1.07417e-06 0.000617202]

**Comment by jmirabel** [comment]
As you mentioned, the inertia matrix in HPP is not a tested feature. You can safely ignore what HPP does on this topic.
